
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 15 09:35:39 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NumeroHexaIMM = 9;
  public static final int Comentario = 7;
  public static final int Equ = 5;
  public static final int CharIMM = 11;
  public static final int Org_Equ = 18;
  public static final int ERROR = 17;
  public static final int Org = 2;
  public static final int Fcb = 3;
  public static final int NumeroHexaEXT = 14;
  public static final int End = 4;
  public static final int NumeroDecIMM = 10;
  public static final int EOF = 0;
  public static final int Linea = 19;
  public static final int error = 1;
  public static final int Etiq_Var_Instrucc = 8;
  public static final int NumeroHexaDIR = 12;
  public static final int NumeroDecDIR_EXT = 13;
  public static final int Espacio = 6;
  public static final int NumeroHexaINDY = 16;
  public static final int NumeroHexaINDX = 15;
}

